server.error:
  include-stacktrace: always
  include-exception: true

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql:lghs_accounting
    username: lghs_accounting_app
    password: 'change-me'

  flyway:
    url: ${spring.datasource.url}
    user: lghs_accounting_root
    password: 'change-me'
    schemas: accounting

  security:
    oauth2:
      client:
        provider:
          members:
            client-id: "${spring.security.oauth2.client.registration.members.client-id}"
            authorization-uri: "https://members.lghs.be/oauth/authorize"
            token-uri: "https://members.lghs.be/oauth/token"
            user-info-uri: "https://members.lghs.be/api/me"
            user-name-attribute: "username"
        registration:
          members:
            client-id: "change-me"
            client-secret: "change-me"
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"

handlebars:
  cache: false
---
spring:
  profiles: prd

handlebars:
  cache: true
