spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql:accounting
    username: lghs_accounting_app
    password: 'change-me'

  flyway:
    url: ${spring.datasource.url}
    user: lghs_accounting_root
    password: 'change-me'
    schemas: accounting

handlebars:
  cache: false

---
spring:
  profiles: prd

handlebars:
  cache: true
