name: accounting
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          docker pull postgres:12
          docker run \
            -p 127.0.0.1:5432:5432 \
            -v $(realpath etc/database.sql):/docker-entrypoint-initdb.d/database.sql \
            postgres:12 &
          sleep 5
          ./gradlew --no-daemon -Dgradle.user.home=etc flywayMigrate
          ./gradlew --no-daemon -Dgradle.user.home=etc generateAccountingJooqSchemaSource
          ./gradlew --no-daemon build
